### ISSUE TITLE
添加电路板

### ISSUE THREAD

**Issue by JankingHuang** [platformio/platform-intel_mcs51#17]
支持stc89c52系列

**Comment by znhocn** [comment]
STC89C52RC 直接使用 STC15W408AS 配置也是可以的。
编译完成的固件保存在项目文件夹的 `.pioenvs` 目录里；下载固件到芯片里可以 STC-ISP 软件工具进行下载。

对于 STC89C52RC 的支持我已经提交了

**Comment by JankingHuang** [comment]
谢谢，你的回复。
