### ISSUE TITLE
dual DPTR support for STC15

### ISSUE THREAD

**Issue by NickLiu635** [platformio/platform-intel_mcs51#23]
STC15 series have dual DPTR, controlled via DPS at 0xA2.0.here's the [document](http://www.stcmcudata.com/datasheet/stc/STC-AD-PDF/STC15-English.pdf)
> P297 3.3.3 Dual Data Pointer Register(DPTR)

SDCC supports it.，p89c51r

https://sourceforge.net/p/sdcc/wiki/8051%20Variants/

----

STC15系列支持双DPTR，[文档地址](http://www.stcmcudata.com/datasheet/stc/STC-AD-PDF/STC15.pdf)
>P397 STC15系列8051 单片机 双数据指针

看起来似乎SDCC支持这种双DPTR模式。
https://sourceforge.net/p/sdcc/wiki/8051%20Variants/
能否让platform-intel_mcs51 支持呢？

**Comment by zerog2k** [comment]
Please see comments on PR #25 

summary:
I don't think those targets exist in current sdcc versions (maybe wiki is outdated?)
Current SDCC manual shows (sec 4.1.2) that dual dptr not supported in `mcs51` target.
