### ISSUE TITLE
VSCode warning：cannot open source file "compiler.h"

### ISSUE THREAD

**Issue by NickLiu635** [platformio/platform-intel_mcs51#24]
>cannot open source file "compiler.h"

>#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit

however，platformIO  warns me that

>!!! WARNING !!! AUTO-GENERATED FILE, PLEASE DO NOT MODIFY IT AND USE https://docs.platformio.org/page/projectconf/section_env_build.html#build-flags

**Comment by ivankravets** [comment]
Could you provide a simple project to reproduce this issue?
