### ISSUE TITLE
Lack of python3 executable on windows causes uploads with stcgal to fail

### ISSUE THREAD

**Issue by mincrmatt12** [platformio/platform-intel_mcs51#27]
Just as the title says -- the build script tries to run `python3 stcgal.py`, and the windows python installer doesn't create this file. One possible solution would be to use the `py -3` wrapper executable.

![build log](https://user-images.githubusercontent.com/5255209/65641380-9815fe00-dfba-11e9-9380-ad21b33306c0.png)

**Comment by ivankravets** [comment]
Should be fixed in the latest version
