### ISSUE TITLE
framework-nakedmcs51 sha1 hash does not match

### ISSUE THREAD

**Issue by zerog2k** [platformio/platform-intel_mcs51#3]
getting an error when trying to run on ubuntu linux 16.04

```
> Executing task: platformio run <

[Sat Jan  6 20:45:23 2018] Processing stc15f204ea (platform: mcs51; board: stc15f204ea; framework: naked)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PackageManager: Installing framework-nakedmcs51 @ ~0.0.1
Downloading  [####################################]  100%
Warning! Package Mirror: The 'sha1' sum '7f29f4aaa221b4c693a2597ab4fc8ff4d42cd229' of downloaded file 'framework-nakedmcs51-0.0.2.tar.gz' is not equal to remote 'f57367a56d251cd8bc1eab0d9c282c06e8b1bd12'
Looking for other mirror...
Error: Could not install 'framework-nakedmcs51' with version requirements '~0.0.1' for your system 'linux_x86_64'.
 If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

```

note the stc15f204ea is my attempt at developing alternate boards (for stc mcu's).
But this seems to be some issue with the hosted downloads mismatched with hashes.

**Comment by zerog2k** [comment]
```
$ curl https://dl.bintray.com/palatis/platformio-dl-packages/manifest.json
{
    "framework-nakedmcs51":
    [
        {
            "url": "https://github.com/Palatis/framework-nakedmcs51/archive/v0.0.2.tar.gz",
            "sha1": "f57367a56d251cd8bc1eab0d9c282c06e8b1bd12",
            "version": "0.0.2",
            "system": "all"
        }
```

but this doesnt match the tgz archive at that url, which is:
7f29f4aaa221b4c693a2597ab4fc8ff4d42cd229  v0.0.2.tar.gz

**Comment by zerog2k** [comment]
ok i see this is probably coming from the binary archive you compiled from the framework:
https://github.com/Palatis/framework-nakedmcs51

I think I'm able to bypass this if i do not select a framework in my platformio.ini

**Comment by ivankravets** [comment]
@Palatis Would like to transfer this repo to @PlatformIO organization and we will maintain it togehter? Also, will add it to our registry where other people can use without extra steps.

Thanks a lot for your work!

**Comment by Palatis** [comment]
sure that'd be fine, I probably won't be working on this mcs51 platform support recently, tho.

working on esp32 rite now.

**Comment by ivankravets** [comment]
Please navigate to repo settings and trasfer it to https://github.com/platformio

Your all contribution will be saved under your name.

**Comment by Palatis** [comment]
hmm... I hit "Transfer" and entered the name of the repo and "platformio" for "New owner’s GitHub username or organization name", but it says i don't have permission to create repo on platformio.

**Comment by ivankravets** [comment]
I granted you global permission. Could you try again?

**Comment by Palatis** [comment]
still, says "You don’t have the permission to create repositories on platformio"
maybe you have to grant some repo permission.

i planned to transfer
- https://github.com/Palatis/platform-mcs51
- https://github.com/Palatis/framework-nakedmcs51
- https://github.com/Palatis/toolchain-sdcc
over to @platformio

**Comment by ivankravets** [comment]
Ok, increased permissions again. Could you try now?

**Comment by Palatis** [comment]
transferred :-D
now you can ungrant the unneccesory permissions.

**Comment by ivankravets** [comment]
Thank you very much! I granted you all permissions to these repositories. Would be thankful for any help! ;)

**Comment by ivankravets** [comment]
Fixed
