### ISSUE TITLE
CH55x support

### ISSUE THREAD

**Issue by Tonymac32** [platformio/platform-intel_mcs51#30]
The CH55x family of micro controllers are MCS-51 based USB IC's, ranging from single USB device to dual USB host devices.  I opened a PR to get CH559 support, https://github.com/platformio/platform-intel_mcs51/pull/29

A couple items, the python uploader needs pulled from an external repository, and depends on libusb.  

Thank you!

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-intel_mcs51/commit/81bf8cc30f33d1926efdb1f80a2d6802e7c1f378
