### ISSUE TITLE
stcgal and sdcc

### ISSUE THREAD

**Issue by totollo** [platformio/platform-intel_mcs51#32]
please update stcgal to 1.6 and sdcc to 4.0 . without stcgal 1.6 I can not flash to stc8 chips. thx~~~

**Comment by RomanZw** [comment]
I have a similar problem with STC8C2K32S2:
Processing STC8C2K32S2 (platform: intel_mcs51; board: STC8C2K32S2)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/intel_mcs51/STC8C2K32S2.html
PLATFORM: Intel MCS-51 (8051) (2.1.0) > Generic STC8C2K32S2
HARDWARE: STC8C2K32S2 11MHz, 2.25KB RAM, 32KB Flash
PACKAGES: 
 - tool-stcgal @ 1.106.0 (1.6) 
 - tool-vnproch55x @ 1.0.220407 
 - toolchain-sdcc @ 1.40200.0 (4.2.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 1 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Checking size .pio/build/STC8C2K32S2/firmware.hex
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
Flash: [          ]   3.2% (used 1042 bytes from 32768 bytes)
Configuring upload protocol...
AVAILABLE: stcgal
CURRENT: upload_protocol = stcgal
Looking for upload port...
Using manually specified: /dev/cu.usbserial-B001BS7P
Uploading .pio/build/STC8C2K32S2/firmware.hex
Cycling power: done
WARNING: Unknown model F7DA!
Waiting for MCU: done
Target model:
  Name: UNKNOWN
  Magic: F7DA
  Code flash: 62.0 KB
  EEPROM flash: 0.0 KB
Target frequency: 11.058 MHz
Target BSL version: 7.3.13U
Target wakeup frequency: 34.900 KHz
Target ref. voltage: 1186 mV
Target mfg. date: 2023-05-12
Target options:
  reset_pin_enabled=False
  clock_gain=high
  watchdog_por_enabled=False
  watchdog_stop_idle=False
  watchdog_prescale=256
  low_voltage_reset=True
  low_voltage_threshold=0
  eeprom_erase_enabled=True
  bsl_pindetect_enabled=False
  por_reset_delay=long
  rstout_por_state=high
  uart1_remap=False
  uart2_passthrough=True
  uart2_pin_mode=push-pull
  epwm_open_drain=True
  program_eeprom_split=32768
Loading flash: 1042 bytes (Intel HEX)
Trimming frequency: 11.062 MHz
Switching to 38400 baud: done
Serial port error: read timeout
*** [upload] Error 1
