### ISSUE TITLE
Please update the sdcc version in toolchain-sdcc

### ISSUE THREAD

**Issue by wc7086** [platformio/platform-intel_mcs51#54]
I noticed that sddc has been updated to 4.4.0, while the version used by the library is still stuck at 4.2.0, and I didn't find anything that would provide pr for the build script.

@ivankravets

**Comment by ivankravets** [comment]
> platform = https://github.com/platformio/platform-intel_mcs51.git

Please re-test with `platform = https://github.com/platformio/platform-intel_mcs51.git`, update in `platformio.ini`. Navigate via CLI to the project folder and run `pio pkg update`.

Does it work?

**Comment by ivankravets** [comment]
It seems like the new toolchain is not compatible with our examples. See https://github.com/platformio/platform-intel_mcs51/actions/runs/8271696808/job/22632035067

Could you provide a FIX/PR to https://github.com/platformio/platform-intel_mcs51/tree/develop/examples/native-blink ?

cc @zaoshang67dian , @MainWire, @hhgyu
