### ISSUE TITLE
"CC" non \x8a riconosciuto come comando interno o esterno,  un programma eseguibile o un file batch.

### ISSUE THREAD

**Issue by MainWire** [platformio/platform-intel_mcs51#55]
# Issue : Simple config problem or possible bug

I was told to open an issue here because this could be a BUG

## Configuration
Operating system: Win 10 x64
PlatformIO core Version (core --version): 6.1.13
PlatformIO extension: 							  3.3.3
C++ extension version: 							  1.19.4

## Description of problem
Getting the error `"CC" non \x8a riconosciuto come comando interno o esterno,  un programma eseguibile o un file batch.` when trying to compile **CPP** file on CH559 board

I am able to successfully compile the projet with platformio, when using **any C file**.
However, **as soon as I try to use a _CPP_ file**, I get the mentionned error in the build process.

I tried deleting the cache, packages, platform folders, and reinstalling cpp and platformio extensions, but couldn't get it to work.
I already wrote on an existing issue, where I was told to open an issue here. [Issue #4149](https://github.com/platformio/platformio-core/issues/4149#issuecomment-1935637991)

## 	Actual Results
```
* Executing task in folder trhsyjtujyr: C:\Users\mainwire\.platformio\penv\Scripts\platformio.exe run

Processing CH559 (platform: intel_mcs51; board: CH559)
----------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/intel_mcs51/CH559.html
PLATFORM: Intel MCS-51 (8051) (2.1.0) > CH559
HARDWARE: CH559 12MHz, 6.25KB RAM, 64KB Flash
PACKAGES:
- toolchain-sdcc @ 1.40200.0 (4.2.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 0 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Compiling .pio\build\CH559\src\main.rel
"CC" non \x8a riconosciuto come comando interno o esterno,
un programma eseguibile o un file batch.
*** [.pio\build\CH559\src\main.rel] Error 1
================================= [FAILED] Took 0.72 seconds =================================
* The terminal process "C:\Users\mainwire\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.
* Terminal will be reused by tasks, press any key to close it.
```

## Expected Results
Compiles fine

## 	Board definition :
```
    {
      "build": {
        "f_cpu": "12000000L",
        "size_iram": 256,
        "size_xram": 6144,
        "size_code": 65536,
        "size_heap": 128,
        "mcu": "ch559",
        "cpu": "mcs51"
      },
      "frameworks": [],
      "upload": {
        "maximum_ram_size": 6400,
        "maximum_size": 65536,
        "protocol": "ch55x"
      },
      "name": "CH559",
      "url": "http://www.wch-ic.com/products/CH559.html",
      "vendor": "WCH"
    }
```

## .INI file
```
[env:CH559]
platform = intel_mcs51
board = CH559
build_flags =
  --model-medium
  -LC:%%userprofile%%/.platformio/packages/toolchain-sdcc/lib/medium
  -IC:
  -Isrc/Driver/inc
  -Isrc/PLAT/inc
extra_scripts = link_medium.py
```

## 	link_medium.py file :
https://dpaste.org/0tsqa

## Additional info
I also have a two logs showing up when starting vscode that may explain why the building process fails, but I can't fix that either :
`
[2/25/2024, 12:17:32 PM] Unable to resolve configuration with compilerPath: "C:/Users/mainwire/.platformio/packages/toolchain-sdcc/bin/sdcc.exe"
[2/25/2024, 12:17:32 PM] Unable to resolve configuration with compilerPath: "C:/Users/mainwire/.platformio/packages/toolchain-sdcc/bin/sdcc.exe"
`

Could someone help me with that ?
Feel free to ask if you need any additional information,

Thanks in advance,

**Comment by MainWire** [comment]
Anyone could just give me a hint or anything they think could take the problem a step forward ?

**Comment by MainWire** [comment]
I still haven't found any way to fix that problem. I will be really grateful if anyone could help me. Thanks in advance

**Comment by ivankravets** [comment]
> -LC:%%userprofile%%/.platformio/packages/

Where did you find this buggy code? See https://docs.platformio.org/en/latest/projectconf/interpolation.html

You need `${platformio.packages_dir}`

**Comment by MainWire** [comment]
Thank you for answering ! I updated my config file. However the issue is still the same.
I suppose I should simply add `${platformio.packages_dir}`, I don't need to specify the path of the toolchain ?
Thanks in advance

**Comment by ivankravets** [comment]
> -LC:${platformio.packages_dir}

Please fix it. It should be `-L${platformio.packages_dir}`

**Comment by MainWire** [comment]
> > -LC:${platformio.packages_dir}

Thank you for replying. I updated the line, and I have updated all my sketches to the last native-blink example, according to this issue [toolchain](https://github.com/platformio/platform-intel_mcs51/issues/54).

So far no changes... If anyone ever succeed to compile it I woud be happy to know how 👍
