### ISSUE TITLE
please upgrade the version of stcgal, and check script of tool-stcgal

### ISSUE THREAD

**Issue by zaoshang67dian** [platformio/platform-intel_mcs51#56]
The version of stcgal has upgrade, whitch support some new ic. 
And then please check the script of tool-stcgal, when i upload firmware for stc8h8k64u by pio, it failed. the script of pio attach -P stc8 in the commond line; 
But when i replease the "-P stc8" with "-P auto" and use local stcgal it upload success; 
just like stcgal -P auto -p /dev/ttyxxxxx -t 22481 ./pio/xxxxx/firmware.hex

**Comment by ivankravets** [comment]
Please re-test with 
```
[env:myenv]
platform = https://github.com/platformio/platform-intel_mcs51.git
...
```

Open PlatformIO Core CLI, navigate to the project folder and type

```
$ pio pkg update
```

Does it work?
